version: "3.7"

services:
  db_questio:
    image: postgres
    expose:
      - 5432
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: db_questIO
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - default

  api_questio:
    build:
      context: ./QuestIoAPI
      dockerfile: Dockerfile
    depends_on:
      - db_questio
    ports:
      - "4000:4000"
    restart: always
    networks:
      - default
    environment:
      DATABASE_URL: postgresql://docker:docker@db_questio:5432/db_questIO
      NODE_ENV: production
      API_KEY: quest
      PORT: 4000
    healthcheck:
      test: ["CMD-SHELL", "curl -sS http://localhost:4000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  default:
    driver: bridge

volumes:
  pgdata:
