version: 2.27.0

services:
  api_questIO:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
