version: '3.7'

services:
  db_questio:
    image: postgres
    ports:
      - '5432:5432'
    restart: always
    env_file:
      - .env.db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
